id: P007901
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:48:10.319133
source_metadata:
  id: bdr:W3CN1804
  title: བེམ་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་གྱི་གྲོས་འདེབས་ལས་བྱུང་བ་སྨྱོན་པའི་ཟློས་གར་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  author: ''
  volumes:
    08e8288dea4446d5981e45c67e6236ca:
      image_group_id: I3CN1806
      title: Volume 1 of sems kyis gzhan kho na ji ltar byed yod pa'i rnam thar/
      volume_number: 1
      total_pages: 24
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
