id: P007901
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN1804
  title: བེམ་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་གྱི་གྲོས་འདེབས་ལས་བྱུང་བ་སྨྱོན་པའི་ཟློས་གར་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  author: ''
  volumes:
    1e467cfb6a45454294b7f3f38f052185:
      image_group_id: I3CN1806
      title: ''
      volume_number: 1
      total_pages: 24
ebook_metadata:
  title: བེམ་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་གྱི་གྲོས་འདེབས་ལས་བྱུང་བ་སྨྱོན་པའི་ཟློས་གར་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  author: ''
  sku: P007901
  cover: cover.jpg
  layers:
  - pagination
