id: I0C05C640
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:51:16+00:00'
last_modified: '2022-06-09T07:15:31.395981+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN1804
  title: བེམ་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་གྱི་གྲོས་འདེབས་ལས་བྱུང་བ་སྨྱོན་པའི་ཟློས་གར་གསལ་བར་བྱེད་པའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9119':
      image_group_id: I3CN1806
      title: Volume 1 of sems kyis gzhan kho na ji ltar byed yod pa'i rnam thar/
      total_pages: 24
      order: 1
      base_file: 9119.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
